allowBuilds:
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - '@better-auth/core@1.6.20'
  - '@better-auth/drizzle-adapter@1.6.20'
  - '@better-auth/kysely-adapter@1.6.20'
  - '@better-auth/memory-adapter@1.6.20'
  - '@better-auth/mongo-adapter@1.6.20'
  - '@better-auth/prisma-adapter@1.6.20'
  - '@better-auth/telemetry@1.6.20'
  - better-auth@1.6.20
